# system vars
is_manjaro: "{{ ansible_facts['distribution'] == 'Archlinux' }}"
is_osx: "{{ ansible_facts['distribution'] == 'MacOSX' }}"
become_root: "{{ 'yes' if is_manjaro else 'no' }}"

# data vars
data_dir: "/data/"
dotfiles_dir: "$PWD/../dotfiles"
dotfiles_packages:
  - zsh
  - git
  - config
  - scripts
nvim_repos:
  - repo: git@github.com:NvChad/NvChad.git
    dest: $HOME/.config/nvim
  - repo: git@github.com:marco-souza/nvchad.git
    dest: $HOME/.config/nvim/lua/custom
credentials: 
  - src: "../dotfiles/ssh/id_rsa"
    dest: "$HOME/.ssh/id_rsa"
  - src: "../dotfiles/ssh/id_rsa.pub"
    dest: "$HOME/.ssh/id_rsa.pub"
  - src: "../dotfiles/wakatime/.wakatime.cfg"
    dest: "$HOME/.wakatime.cfg"

# package vars
aur_packages:
  - discord
  - brave-bin
  - 1password
  - 1password-cli
  - pop-wallpapers-git
  - telegram-desktop-bin
  - tailscale-systray-git
  - visual-studio-code-insiders-bin
  - steam-native-runtime

cask_packages:
  - steam
  - iterm2
  - discord
  - amethyst
  - notion
  - 1password
  - 1password-cli
  - brave-browser
  - visual-studio-code-insiders

base_packages:
  - zsh
  - git
  - vim
  - tree
  - stow
  - tmux
  - wget
  - curl
  - make
  - htop

dev_packages:
  - go
  - npm
  - rust
  - deno
  - nodejs
  - tailscale
  - "wakatime{{ '' if is_manjaro else '-cli' }}"

# node vars
node_home: $HOME/.npm-global
npm_packages:
  - yarn
  - pnpm
  - tsx
  - vercel
  - remark
  - emmet-ls
  - typescript
  - '@nestjs/cli'
  # LSP
  - vscode-langservers-extracted
  - typescript-language-server
  - tailwindcss-language-server
  - remark-language-server
  - '@prisma/language-server'
  - '@ansible/ansible-language-server'
  - '@withgraphite/graphite-cli'

