---
- name: Install Gnome Shell
  become: true
  ansible.builtin.package:
    name:
      - gnome-desktop
      - gnome-tweaks
    state: present

- name: Clone material-shell
  ansible.builtin.git:
    repo: git@github.com:material-shell/material-shell.git
    dest: $HOME/.cache/material-shell
    clone: true
    force: true
    update: true
    accept_newhostkey: true

- name: Build & install Gnome Material Shell
  ansible.builtin.shell: |
    cd $HOME/.cache/material-shell
    make install 2>/dev/null

- name: Enable Gnome Extensions
  ansible.builtin.shell: |
    gnome-extensions enable "{{ item }}"
  with_items:
    - material-shell@papyelgringo

- name: Create Terminal shortcut
  ansible.builtin.shell: |
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Terminal'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'zsh -c "alacritty || gnome-terminal"'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>t'
