---
- name: Setup zsh
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - marco

- name: Stow user data (manjaro)
  when: is_manjaro
  ansible.builtin.shell:
    cmd: stow home -t $HOME
    chdir: "{{ data_dir }}"

- name: Stow cofig files
  ansible.builtin.shell:
    cmd: stow {{ item }} -t $HOME
    chdir: "{{ dotfiles_dir }}"
  with_items: "{{ dotfiles_packages }}"

- name: Setup Credentials
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "600"
  with_items: "{{ credentials }}"
