---
- name: Install base packages
  become: yes
  package:
    name:
      - zsh
      - git
      - vim
      - fzf
      - stow
      - tmux
      - neovim
      - ripgrep
      - steam-native-runtime
    state: present

- name: Install AUR packages
  kewlfft.aur.aur:
    use: yay
    name:
      - discord
      - 1password
      - brave-bin
      - 1password-cli
      - visual-studio-code-insiders-bin

- name: Stow user data
  shell:
    cmd: stow home -t $HOME
    chdir: "{{ data_dir }}"

- name: Stow cofig files
  shell:
    cmd: stow {{ item }} -t $HOME
    chdir: "{{ dotfiles_dir }}"
  with_items:
    - zsh
    - git
    - config
    - scripts
    - wakatime

- name: Setup zsh
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - marco

- name: Setup neovim
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
    update: yes
  with_items:
    - repo: https://github.com/AstroNvim/AstroNvim
      dest: $HOME/.config/nvim
    - repo: https://github.com/marco-souza/astronvim
      dest: $HOME/.config/nvim/lua/user

