---
- name: Install base packages
  become: "{{ become_root }}"
  ansible.builtin.package:
    name:
      - fzf
      - neovim
      - ripgrep
    state: present

- name: Setup Personal Neovim config
  ansible.builtin.git:
    repo: git@github.com:marco-souza/nvim.git
    dest: $HOME/.config/nvim
    clone: true
    force: true
    update: true
    accept_newhostkey: true

- name: Initialize Neovim
  ansible.builtin.shell: nvim --headless +"Lazy! sync" +qa

