---
- name: Install Gnome PopOS! shell
  become: yes
  package:
    name:
      - gnome-desktop
      - gnome-shell-extension-pop-shell
      - pop-shell-shortcuts
    state: present

- name: Remap laucher to Alt+Space
  shell: |
    gsettings 
      --schemadir ~/.local/share/gnome-shell/extensions/pop-shell@system76.com/schemas
      set org.gnome.shell.extensions.pop-shell activate-launcher "['<Alt>space']"

# - name: Create keyboard shortcuts for Pop Shell
#   gnome_shortcut:
#     name: "{{ item.name }}"
#     command: "{{ item.command }}"
#     shortcut: "{{ item.shortcut }}"
#   with_items: "{{ pop_shell_shortcuts }}"
