---
- name: Install Gnome PopOS! shell
  become: yes
  package:
    name:
      - gnome-desktop
      - gnome-tweaks
      # pop-os tiling
      - gnome-shell-extension-pop-shell
      - pop-shell-shortcuts
      # pop-os theme
      - pop-gtk-theme
      - gtk-engine-murrine
      - gtk-engines
      - pop-gnome-shell-theme
      - pop-icon-theme
      - pop-sound-theme
      - ttf-fira-sans
      - ttf-fira-mono
      - ttf-roboto-slab
    state: present

- name: Remap PopOS! laucher
  shell: |
    gsettings set org.gnome.shell.extensions.pop-shell  activate-launcher  "['<Super>z']"

# - name: Create keyboard shortcuts for Pop Shell
#   gnome_shortcut:
#     name: "{{ item.name }}"
#     command: "{{ item.command }}"
#     shortcut: "{{ item.shortcut }}"
#   with_items: "{{ pop_shell_shortcuts }}"
