---
- name: Install personal base packages
  when: is_manjaro
  become: yes
  package:
    name:
      - steam-native-runtime
    state: present

- name: Install AUR packages
  when: is_manjaro
  kewlfft.aur.aur:
    use: yay
    name:
      - discord
      - 1password
      - brave-bin
      - 1password-cli
      - pop-wallpapers-git
      - nerd-fonts-fira-code
      - visual-studio-code-insiders-bin
  
- name: Stow user data
  when: is_manjaro
  shell:
    cmd: stow home -t $HOME
    chdir: "{{ data_dir }}"

- name: Tap cask packages
  when: is_osx
  homebrew_tap:
    name:
      - homebrew/cask-versions
      - homebrew/cask-fonts

- name: Install cask packages
  when: is_osx
  homebrew_cask:
    name:
      - steam
      - iterm2
      - discord
      - amethyst
      - 1password
      - 1password-cli
      - brave-browser
      - visual-studio-code-insiders
      # fonts
      - font-hack-nerd-font
      - font-noto-nerd-font
    state: upgraded
