---
- name: Install shared packages (shared)
  become: "{{ is_manjaro }}"
  package:
    name:
      - htop
      - git
      - curl
      - make
    state: present

- name: Install personal base packages (manjaro)
  when: is_manjaro
  become: yes
  package:
    name:
      - steam-native-runtime
    state: present

- name: Install AUR packages (manjaro)
  when: is_manjaro
  kewlfft.aur.aur:
    use: yay
    name:
      - discord
      - 1password
      - brave-bin
      - 1password-cli
      - pop-wallpapers-git
      - telegram-desktop-bin
      - visual-studio-code-insiders-bin
  
- name: Stow user data (manjaro)
  when: is_manjaro
  shell:
    cmd: stow home -t $HOME
    chdir: "{{ data_dir }}"

- name: Tap cask packages (osx)
  when: is_osx
  homebrew_tap:
    name:
      - homebrew/cask-versions
      - homebrew/cask-fonts

- name: Install cask packages (osx)
  when: is_osx
  homebrew_cask:
    name:
      - steam
      - iterm2
      - discord
      - amethyst
      - notion
      - 1password
      - 1password-cli
      - brave-browser
      - visual-studio-code-insiders
    state: upgraded

- name: Install Nerd fonts (osx)
  when: is_osx
  shell: "brew search '/font-.*-nerd-font/' | awk '{ print $1 }' | xargs brew install --cask || true"
