# system vars
is_manjaro: "{{ ansible_facts['distribution'] == 'Archlinux' }}"
is_osx: "{{ ansible_facts['distribution'] == 'MacOSX' }}"
become_root: "{{ 'yes' if is_manjaro else 'no' }}"

# data vars
data_dir: /data/

# dotfiles onfigs
dotfiles_dir: $PWD/../../dotfiles
dotfiles_packages:
  - zsh
  - git
  - config
  - helix
  - scripts
  - hyprland

obsidian_repos:
  - repo: git@github.com:marco-souza/notes.git
    dest: $HOME/w/marco-souza/notes

credentials:
  - src: ../dotfiles/ssh/id_rsa
    dest: $HOME/.ssh/id_rsa
  - src: ../dotfiles/ssh/id_rsa.pub
    dest: $HOME/.ssh/id_rsa.pub
  - src: ../dotfiles/wakatime/.wakatime.cfg
    dest: $HOME/.wakatime.cfg

# package vars
aur_packages:
  - ollama
  - discord
  - wakatime
  - brave-bin
  - tailscale
  - 1password
  - obsidian-bin
  - google-chrome
  - pop-wallpapers-git
  - steam-native-runtime
  - telegram-desktop-bin

cask_packages:
  - arc
  - steam
  - ollama
  - discord
  - amethyst
  - wakatime
  - obsidian
  - telegram
  - 1password
  - tailscale
  - brave-browser
  - google-chrome

base_packages:
  - zsh
  - git
  - vim
  - tree
  - stow
  - tmux
  - wget
  - curl
  - make
  - htop
  - gnupg

# node vars
node_home: $HOME/.npm-global
npm_packages: [] # TODO: replace with volta or remove
