# system vars
is_manjaro: "{{ ansible_facts['distribution'] == 'Archlinux' }}"
is_osx: "{{ ansible_facts['distribution'] == 'MacOSX' }}"
become_root: "{{ 'yes' if is_manjaro else 'no' }}"

# data vars
data_dir: /data/

# dotfiles

dotfiles_dir: ../../dotfiles 
dotfiles_packages:
  - zsh
  - git
  - config
  - ghostty
  # - wakatime # INFO: configured as credential
  - helix
  - scripts
  - hyprland

credentials:
  - src: "{{dotfiles_dir}}/ssh/id_rsa"
    dest: $HOME/.ssh/id_rsa

  - src: "{{dotfiles_dir}}/ssh/id_rsa.pub"
    dest: $HOME/.ssh/id_rsa.pub

  - src: "{{dotfiles_dir}}/wakatime/.wakatime.cfg"
    dest: $HOME/.wakatime.cfg

# package vars
aur_packages:
  - ollama
  - discord
  - ghostty
  - wakatime
  - brave-bin
  - tailscale
  - 1password
  - obsidian
  - google-chrome
  - zen-browser-bin
  - steam-native-runtime
  - telegram-desktop-bin

cask_packages:
  - steam
  - ollama
  - discord
  - ghostty
  - amethyst
  - wakatime
  - obsidian
  - telegram
  - 1password
  - tailscale
  - zen-browser
  - brave-browser
  - google-chrome

base_packages:
  - zsh
  - git
  - vim
  - tree
  - stow
  - tmux
  - wget
  - curl
  - make
  - htop
  - gnupg
  # languages
  - go
  - zig
  - rust

# node vars
node_home: $HOME/.npm-global
npm_packages: 
  - npm

obsidian_repos:
  - repo: git@github.com:marco-souza/notes.git
    dest: $HOME/w/marco-souza/notes
