# Good themes:
#
# boogster ayu_mirage boo_berry dark_plus
# everblush ferra fleet_dark github_dark
# github_dark_dimmed jellybeans kanagawa
# kaolin-valley-dark material_deep_ocean
# molokai nightfox nord-light snazzy sonokai
theme = "onedarker"

[editor]
line-number = "relative"
mouse = false
rulers = [80,120]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme onedarker"]
