---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: "{{ cache_timeout }}"

- name: Reboot a slow machine that might have lots of updates to apply
  reboot:
    reboot_timeout: "{{ reboot_timeout }}"
