---
- name: (arch) Install
  become: "{{ become_root }}"
  when: is_manjaro
  ansible.builtin.package:
    name:
      - obsidian-bin
    state: present

- name: (osx) Install
  when: is_osx
  community.general.homebrew_cask:
    name:
      - obsidian

- name: Setup vaults
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: true
    force: true
    update: true
    accept_newhostkey: true
  with_items: "{{ obsidian_repos }}"
