---
- name: (shared) Install base packages
  become: "{{ is_manjaro }}"
  ansible.builtin.package:
    state: present
    name: "{{ base_packages }}"

- name: (shared) Install dev packages
  become: "{{ become_root }}"
  ansible.builtin.package:
    state: present
    name: "{{ dev_packages }}"

- name: (manjaro) Install AUR packages
  when: is_manjaro
  kewlfft.aur.aur:
    use: yay
    name: "{{ aur_packages }}"

- name: (osx) Install cask packages
  when: is_osx
  community.general.homebrew_cask:
    state: upgraded
    name: "{{ cask_packages }}"

- name: (osx) Tap cask packages
  when: is_osx
  community.general.homebrew_tap:
    name:
      - homebrew/cask-versions
      - homebrew/cask-fonts

- name: (osx) Install Nerd fonts
  when: is_osx
  ansible.builtin.shell: |
    brew search '/font-.*-nerd-font/' | awk '{ print $1 }' | xargs brew install --cask || true
