---
- name: (arch) Install podman packages
  become: "{{ become_root }}"
  when: is_manjaro
  ansible.builtin.package:
    name:
      - podman
      - podman-desktop
    state: present

- name: (osx) Install podman packages
  when: is_osx
  community.general.homebrew_cask:
    name:
      - podman
      - podman-desktop
