---
- name: Install dev packages
  become: "{{ become_root }}"
  package:
    name:
      - go
      - npm
      - rust
      - deno
      - nodejs
      - docker
      - docker-compose
      - "wakatime{{ '' if is_manjaro else '-cli' }}"
    state: present

- name: Create global NPM_HOME
  file:
    path: $HOME/.npm-global
    state: directory
    mode: '0755'

- name: Set node prefix
  shell: npm config set prefix $HOME/.npm-global

- name: Install NPM packages
  npm:
    name: "{{ item }}"
    global: true
    state: present
  with_items:
    - yarn
    - pnpm
    - tsx
    - vercel
    - emmet-ls
    - typescript
    - typescript-language-server
    - tailwindcss-language-server
