---
- name: Install dev packages
  become: "{{ become_root }}"
  package:
    name:
      - go
      - npm
      - rust
      - deno
      - nodejs
      - tailscale
      - "wakatime{{ '' if is_manjaro else '-cli' }}"
    state: present

- name: Install docker packages
  become: "{{ become_root }}"
  when: is_manjaro
  package:
    name:
      - docker
      - docker-compose
      - docker-machine
    state: present

- name: Install cask docker packages
  when: not is_manjaro
  homebrew_cask:
    name:
      - docker

- name: Create global NPM_HOME
  file:
    path: $HOME/.npm-global
    state: directory
    mode: '0755'

- name: Set node prefix
  shell: npm config set prefix $HOME/.npm-global

- name: Install NPM packages
  npm:
    name: "{{ item }}"
    global: true
    state: present
  with_items: "{{ npm_packages }}"

