---
- name: (arch) Install docker packages
  become: "{{ become_root }}"
  when: is_manjaro
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
      - docker-machine
    state: present

- name: (osx) Install docker packages
  when: is_osx
  community.general.homebrew_cask:
    name:
      - docker
