---
- name: Install base packages
  become: yes
  package:
    name:
      - zsh
      - git
      - vim
      - fzf
      - tree
      - stow
      - tmux
      - neovim
      - ripgrep
    state: present

- name: Stow cofig files
  shell:
    cmd: stow {{ item }} -t $HOME
    chdir: "{{ dotfiles_dir }}"
  with_items:
    - zsh
    - git
    - config
    - scripts

- name: Setup zsh
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - marco

- name: Setup neovim
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
    update: yes
  with_items:
    - repo: https://github.com/AstroNvim/AstroNvim
      dest: $HOME/.config/nvim
    - repo: https://github.com/marco-souza/astronvim
      dest: $HOME/.config/nvim/lua/user

- name: Setup Credentials
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '600'
  with_items:
    - src: "./dotfiles/ssh/id_rsa"
      dest: "$HOME/.ssh/id_rsa"
    - src: "./dotfiles/ssh/id_rsa.pub"
      dest: "$HOME/.ssh/id_rsa.pub"
    - src: "./dotfiles/wakatime/.wakatime.cfg"
      dest: "$HOME/.wakatime.cfg"
