shortcuts:
  - schema: org.gnome.desktop.wm.keybindings
    shortcut: "['<Super><Control><Shift>Right', '<Super><Control><Shift>KP_Right', '<Super><Control><Shift>l']"
    command: 'move-to-workspace-right'
  - schema: org.gnome.desktop.wm.keybindings
    shortcut: "['<Super><Control><Shift>Left', '<Super><Control><Shift>KP_Left', '<Super><Control><Shift>h']"
    command: 'move-to-workspace-left'
  - schema: org.gnome.desktop.wm.keybindings
    shortcut: "['<Super><Control>Right', '<Super><Control>KP_Right', '<Super><Control>l']"
    command: 'switch-to-workspace-right'
  - schema: org.gnome.desktop.wm.keybindings
    shortcut: "['<Super><Control>Left', '<Super><Control>KP_Left', '<Super><Control>h']"
    command: 'switch-to-workspace-left'
  # PopOS shortcuts
  - schema: org.gnome.shell.extensions.pop-shell
    shortcut: "['<Super>z']"
    command: 'activate-launcher'
  - schema: org.gnome.shell.extensions.pop-shell
    shortcut: "['<Super>Left', '<Super>KP_Left', '<Super>h']"
    command: 'focus-left'
  - schema: org.gnome.shell.extensions.pop-shell
    shortcut: "['<Super>Right', '<Super>KP_Right', '<Super>l']"
    command: 'focus-right'
