---
- name: Setup Gnome Desktop
  hosts: localhost
  roles:
    # system
    - fonts
    - install_packages
    - dotfiles
    # tools
    - hyprland
    - obsidian
    - neovim
    - podman
    - node
