---
- name: Install base packages
  become: "{{ become_root }}"
  ansible.builtin.package:
    name:
      - fzf
      - neovim
      - ripgrep
    state: present

- name: Setup neovim
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: true
    force: true
    update: true
    accept_newhostkey: true
  with_items: "{{ nvim_repos }}"
